# Generated by Django 3.2.3 on 2021-08-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='クラン名')),
                ('description', models.TextField(max_length=255, verbose_name='説明文')),
            ],
            options={
                'db_table': 'clans',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='名前')),
                ('is_Sniper', models.BooleanField(default=False, verbose_name='SRか')),
                ('memo', models.TextField(max_length=255, null=True, verbose_name='メモ')),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.clan')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
