# Generated by Django 3.2.6 on 2021-08-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberwakes',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='memberwakes',
            name='wake_id',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberWakes',
        ),
        migrations.DeleteModel(
            name='Wake',
        ),
    ]
