# Generated by Django 3.2.6 on 2021-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wake',
            name='description',
            field=models.CharField(blank=True, default='', max_length=48, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='wake',
            name='member',
            field=models.ManyToManyField(related_name='members', related_query_name='member', to='wakes.Member'),
        ),
    ]
